services:
  synapse:
    build:
      context: ../../.
      dockerfile: Dockerfile.synapse
    healthcheck:
      test: ["CMD", "test", "-S", "/tmp/synapse.sock"]
      interval: 2s
      timeout: 1s
      retries: 5
    networks:
      - local_net
      - remote_net
    volumes:
      - shared-sockets:/tmp
    environment:
      - SYNAPSE_REDIS_URL=redis://redis:6379
      - SYNAPSE_REDIS_PREFIX="synapse:cache:"
      - SYNAPSE_REDIS_CHANNEL="synapse:cache_updates"

  synapse2:
    build:
      context: ../../.
      dockerfile: Dockerfile.synapse
    healthcheck:
      test: ["CMD", "test", "-S", "/tmp/synapse2.sock"]
      interval: 2s
      timeout: 1s
      retries: 5
    networks:
      - local_net
      - remote_net
    volumes:
      - shared-sockets:/tmp
    environment:
      - SYNAPSE_SOCKET_PATH=/tmp/synapse2.sock
      - SYNAPSE_REDIS_URL=redis://redis:6379
      - SYNAPSE_REDIS_PREFIX="synapse:cache:"
      - SYNAPSE_REDIS_CHANNEL="synapse:cache_updates"

  web:
    build:
      context: ../../.
      dockerfile: examples/fastapi/Dockerfile.app
    ports:
      - "8000:8000"
    networks:
      - local_net
      - remote_net
    volumes:
      - shared-sockets:/tmp
      - ./main.py:/app/main.py
      - ../data/big_payload.json:/app/big_payload.json:ro
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - synapse
      - synapse2

  redis:
    image: redis:7-alpine
    networks:
      - remote_net

volumes:
  shared-sockets:

networks:
  local_net:
    driver: bridge
  remote_net:
    driver: bridge
