[package]
name = "synapse-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
synapse-core = { path = "../synapse-core" }

tokio = { version = "1.49.0", features = ["full"] }
tokio-util = { version = "0.7.18", features = ["codec"] }
futures = "0.3.31"
